name: Publish Python package

on:
  push:
    tags:
      - "*"

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/represent
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@2473ec6c6aa87f38946284d51289219fd0b87264 # release/v1
        with:
          attestations: true
